# Generated by Django 4.2.2 on 2023-06-25 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(default=None, max_length=10, unique=True)),
                ('flight_name', models.CharField(default=None, max_length=100)),
                ('flight_route', models.CharField(default=None, max_length=100)),
                ('depart_date', models.DateField(default=None)),
                ('depart_time', models.TimeField(default=None)),
                ('depart_loc', models.CharField(default=None, max_length=100)),
                ('total_seats', models.IntegerField(default=60)),
                ('duration', models.CharField(default=None, max_length=50)),
                ('arrival_date', models.DateField(default=None)),
                ('arrival_time', models.TimeField(default=None)),
                ('arrival_loc', models.CharField(default=None, max_length=100)),
                ('price', models.IntegerField(default=None)),
                ('logo', models.ImageField(default=None, upload_to='files/thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booked_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
