# Generated by Django 4.2.2 on 2023-06-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_route',
        ),
    ]
